name: Lint Test Deploy

on: push

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug - List Files
        run: ls -R

      - name: Debug - Check package.json
        run: cat package.json || echo "package.json not found!"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint || echo "Linting failed"

  test:
    name: Run Tests with Vitest
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test || echo "Tests failed"

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy
        run: echo "Deploying..."
